Create expandable table row for table
Pizza-Wallet-Development-team/pizza-wallet pull request #49
Opened 2022-08-30 10:12 UTC by gitChimp88

add mockdata and create expandable row from that data, stopping point

2022-09-09 10:45 UTC, nunocgoncalves requested changes
@gitChimp88, This is some really good progress.
That's exactly the logic we want to follow for the table formatting and filtering.

There is only a small bug I came across and I raised a task on ClickUp. Check it out [here](https://app.clickup.com/t/3gupuvt) for more details.

2022-09-12 08:43 UTC, gitChimp88 commented
@nunocgoncalves Okay I changed the way I was positioning the first column of the dropdown which helps the movement caused by that, but the columns still resize to fit long text (so it doesn't overlap with other columns) we can use a fixed width but then we would need to limit the number of digits or amount of text allowed in each column to avoid overlap.

2022-09-12 15:16 UTC, nunocgoncalves commented
@gitChimp88, Let's use 7 digits for every integer and resize the columns accordingly. Example: 6 -> 6.000000; 60,000 -> 60,000.00

2022-09-19 19:51 UTC, nunocgoncalves commented on src/components/ERC20Balance.jsx
> +  };
Good work, nice and concise.

2022-09-19 19:51 UTC, nunocgoncalves commented on src/index.css
> +  padding: 5px 4px 16px 4px;
Let's covert this values to "em"

2022-09-19 19:51 UTC, nunocgoncalves commented on src/components/reusable/Table.jsx
> +  border-spacing: 0px;
Let's convert this to "em"

2022-10-13 16:11 UTC, nunocgoncalves commented
Task linked: [CU-3j8nf1w Toggleable Dropdown for Table Row](https://app.clickup.com/t/3j8nf1w)

2022-12-17 15:23 UTC, nunocgoncalves commented
@gitChimp88, we can close this, right?

2023-01-04 15:25 UTC, nunocgoncalves commented
Used in #79

2023-01-04 15:25 UTC, closed without merging